# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Greek Life' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	pod ‘Firebase’
	pod 'Firebase/Database'
	pod 'Firebase/Auth’
	pod ‘Firebase/Storage’
	pod 'IQKeyboardManagerSwift'
	pod 'Whisper'
  use_frameworks!

  # Pods for Greek Life

  target 'Greek LifeTests' do
	pod ‘Firebase’	
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod ‘Firebase/Storage’
    inherit! :search_paths
    # Pods for testing
  end

  target 'Greek LifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
